### ISSUE TITLE
Error on running test

### ISSUE THREAD

**Issue by petta** [jammi/mows#1]
I have problem to run tests. exec-function not found.

<code>npm test</code>

> mowsjs@0.0.1 test /Users/petteri/projects/mows
> ./test/run-tests.coffee
> 
> TypeError: undefined is not a function
>  at initTestData (/Users/petteri/projects/mows/test/init-tests.coffee:12:5)
>  at module.exports (/Users/petteri/projects/mows/test/init-tests.coffee:89:3)
>  at startDeps (/Users/petteri/projects/mows/test/run-tests.coffee:16:7)
>  at Object.<anonymous> (/Users/petteri/projects/mows/test/run-tests.coffee:21:1)
>  at Object.<anonymous> (/Users/petteri/projects/mows/test/run-tests.coffee:2:1)
>  at Module._compile (module.js:456:26)
> 
> npm ERR! Test failed.  See above for more details.

**Comment by jammi** [comment]
Should be up to date by now.
